---
- name: copy kubernetes repo
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo

- name: install kube
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: copy kubeadm config
  template:
    src: kubeadm.conf
    dest: /tmp/kubeadm.conf

- name: change ip
  lineinfile:
    dest: /tmp/kubeadm.conf
    regexp: '  advertiseAddress: 0.0.0.0'
    line: '  advertiseAddress: {{ ansible_all_ipv4_addresses[0] }}'
- name: copy join file
  copy:
    src: /tmp/joinkube.sh
    dest: /tmp/joinkube.sh

- name: join kube
  shell: sh /tmp/joinkube.sh
